# Generated by Django 5.1.6 on 2025-02-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="content",
            field=models.CharField(max_length=280),
        ),
    ]
